spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skill_sample
    username: SAMPLER
    password: zmfdlvlt880
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true